apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: users-service
  name: users-service
spec:
  ports:
    - name: 9000-9000
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: users-service
  type: ClusterIP
